import streamlit as st
import cv2
import numpy as np
from ultralytics import YOLO
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
import time
import tempfile

# --- PAGE CONFIG ---
st.set_page_config(
    page_title="Industrial Safety System",
    page_icon="👷‍♂️",
    layout="wide"
)

# ---- GLOBAL STATE FIX ----
if "last_output_frame" not in st.session_state:
    st.session_state.last_output_frame = None

if "video_logs" not in st.session_state:
    st.session_state.video_logs = []


# --- DARK THEME ---
st.markdown("""
    <style>
    .stApp { background-color:#1E1E1E; color:white; }
    [data-testid="stSidebar"] { background:#2a2a2a; }
    </style>
""", unsafe_allow_html=True)

# --- SIDEBAR ---
with st.sidebar:
    st.title("⚙️ Control Panel")

    confidence = st.slider("Model Confidence", 0.25, 1.0, 0.45)
    crowd_limit = st.number_input("Crowd Threshold", min_value=1, value=5)

    st.subheader("📧 Email Setup")
    enable_email = st.checkbox("Enable Email Alerts")
    email_sender = st.text_input("Sender Email", "your@gmail.com")
    email_password = st.text_input("App Password", type="password")
    email_receiver = st.text_input("Receiver Email", "admin@gmail.com")


# --- MODEL LOADING ---
@st.cache_resource
def load_model():
    return YOLO("PPE_Model.pt")

try:
    model = load_model()
except Exception as e:
    st.error(f"Model Load Error: {e}")
    st.stop()


# ================================================================
#  EMAIL FUNCTION (HTML REPORT)
# ================================================================
def send_email_alert(subject, location, timestamp, violations, total_objects, image_bytes):

    if not enable_email:
        return False

    try:
        html_content = f"""
        <html>
        <body style="font-family:Arial; padding:20px;">
            <h2 style="color:#d9534f;">PPE Violation Report</h2>

            <p><b>Location:</b> {location}</p>
            <p><b>Time:</b> {timestamp}</p>

            <hr>

            <h4>Violations Detected:</h4>
            <ul>
                {''.join([f"<li>{v.upper()}</li>" for v in violations])}
            </ul>

            <p><b>Total Objects Flagged:</b> {total_objects}</p>

            <p>Please check the attached image for specific masking details.</p>

            <hr>
            <p style="font-size:14px;color:gray;">
            This is an automated safety alert generated by your PPE Monitoring System.
            </p>
        </body>
        </html>
        """

        msg = MIMEMultipart()
        msg["Subject"] = subject
        msg["From"] = email_sender
        msg["To"] = email_receiver
        msg.attach(MIMEText(html_content, "html"))

        # Attach image
        part = MIMEBase("application", "octet-stream")
        part.set_payload(image_bytes)
        encoders.encode_base64(part)
        part.add_header("Content-Disposition", "attachment; filename=violation.jpg")
        msg.attach(part)

        # SMTP SEND
        s = smtplib.SMTP("smtp.gmail.com", 587)
        s.starttls()
        s.login(email_sender, email_password)
        s.send_message(msg)
        s.quit()

        return True

    except Exception as e:
        st.sidebar.error(f"Email Failed: {e}")
        return False


# ================================================================
#  FRAME PROCESSOR
# ================================================================
def process_frame(frame, conf_threshold):
    results = model(frame, conf=conf_threshold)
    person_count = 0
    violation_tags = []

    for r in results:
        for box in r.boxes:

            x1, y1, x2, y2 = map(int, box.xyxy[0])
            cls = int(box.cls[0])
            label = model.names[cls]
            conf = float(box.conf[0])

            color = (0, 255, 0)

            if label in ['unsafe', 'no helmet', 'no jacket']:
                color = (0, 0, 255)
                violation_tags.append(label)

            if label in ['unsafe', 'safe', 'person', 'no helmet', 'no jacket']:
                person_count += 1

            cv2.rectangle(frame, (x1, y1), (x2, y2), color, 2)
            cv2.putText(frame, f"{label} {conf:.2f}", (x1, y1 - 3),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.45, color, 2)

    return frame, person_count, len(violation_tags), violation_tags


# ================================================================
# MAIN UI
# ================================================================

st.title("🏭 Industrial Safety Monitoring System")
st.markdown("---")

tab1, tab2, tab3 = st.tabs(["📹 Live Camera", "📂 Upload Video/Image", "ℹ️ About"])


# ================================================================
# TAB 1 — LIVE CAMERA
# ================================================================
with tab1:
    col1, col2 = st.columns([4, 1])

    with col1:
        start_cam = st.button("Start Camera")
        stop_cam = st.button("Stop Camera")
        cam_frame = st.empty()

    with col2:
        st.subheader("Live Stats")
        ppl = st.metric("People", 0)
        vio = st.metric("Violations", 0)

    if start_cam:
        cap = cv2.VideoCapture(0)

        while cap.isOpened() and not stop_cam:
            ret, frame = cap.read()
            if not ret:
                break

            frame = cv2.resize(frame, (640, 360))
            frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

            out, p_count, v_count, _ = process_frame(frame_rgb, confidence)
            st.session_state.last_output_frame = out

            cam_frame.image(out, channels="RGB")
            ppl.metric("People", p_count)
            vio.metric("Violations", v_count)

        cap.release()


# ================================================================
# TAB 2 — UPLOAD IMAGE / VIDEO
# ================================================================
with tab2:
    uploaded = st.file_uploader("Upload Video/Image", type=['mp4', 'avi', 'mov', 'jpg', 'png'])

    if uploaded:
        ext = uploaded.name.split(".")[-1].lower()

        # --------------------------------------------------
        # IMAGE PROCESSING
        # --------------------------------------------------
        if ext in ["jpg", "jpeg", "png"]:
            img = cv2.imdecode(np.frombuffer(uploaded.read(), np.uint8), 1)
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

            out, p_count, v_count, tags = process_frame(img, confidence)
            st.session_state.last_output_frame = out

            st.image(out, channels="RGB")
            st.info(f"People: {p_count} | Violations: {v_count}")

            # EMAIL BUTTON FIXED
            if enable_email:
                if st.button("📧 Send Email Report"):
                    img_bytes = cv2.imencode('.jpg', st.session_state.last_output_frame)[1].tobytes()

                    success = send_email_alert(
                        subject="PPE Violation Report",
                        location="Construction Site Zone A",
                        timestamp=time.strftime("%Y-%m-%d %H:%M:%S"),
                        violations=set(tags),
                        total_objects=v_count,
                        image_bytes=img_bytes
                    )

                    if success:
                        st.success("Email Sent Successfully!")
                    else:
                        st.error("Email Failed! Check SMTP or App Password.")

        # --------------------------------------------------
        # VIDEO PROCESSING
        # --------------------------------------------------
        else:
            temp = tempfile.NamedTemporaryFile(delete=False, suffix=f".{ext}")
            temp.write(uploaded.read())

            st.success("Video Loaded. Click Start.")

            if st.button("▶️ Start Video Processing"):
                st.session_state.video_logs = []
                cap = cv2.VideoCapture(temp.name)

                video_col, side_col = st.columns([4, 1])
                video_box = video_col.empty()
                vio_box = side_col.empty()

                while cap.isOpened():
                    ret, frame = cap.read()
                    if not ret:
                        break

                    frame = cv2.resize(frame, (640, 360))
                    frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

                    out, p_count, v_count, tags = process_frame(frame_rgb, confidence)
                    st.session_state.last_output_frame = out

                    video_box.image(out, channels="RGB")
                    vio_box.metric("Violations", v_count)

                    for t in tags:
                        st.session_state.video_logs.append(t)

                cap.release()
                st.success("Processing Completed!")

            st.markdown("### 📄 Detected Violations")

            if len(st.session_state.video_logs) == 0:
                st.info("No violations detected.")
            else:
                st.write(st.session_state.video_logs)

                if enable_email:
                    if st.button("📧 Send Summary to Email"):
                        unique_violations = sorted(set(st.session_state.video_logs))

                        img_bytes = cv2.imencode('.jpg', st.session_state.last_output_frame)[1].tobytes()

                        success = send_email_alert(
                            subject="PPE Violation Report",
                            location="Construction Site Zone A",
                            timestamp=time.strftime("%Y-%m-%d %H:%M:%S"),
                            violations=unique_violations,
                            total_objects=len(unique_violations),
                            image_bytes=img_bytes
                        )

                        if success:
                            st.success("Email Sent!")
                        else:
                            st.error("Email Failed!")

# ================================================================
# TAB 3 — ABOUT
# ================================================================
with tab3:
    st.write("Industrial Safety Monitoring using YOLO + Streamlit.")
